line_length:
- 200 # warning
- 300 # error
function_parameter_count: 
- 8 # warning
- 20 # error
disabled_rules:
- trailing_whitespace
- force_try
- force_cast
- redundant_string_enum_value
- identifier_name
- type_name
- line_length
- function_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
type_body_length:
- 400 # warning
- 500 # error
