platform :ios, '11.0'
#source 'https://github.com/CocoaPods/Specs.git'

target 'EldritchHorrorCards' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  # pod 'Alamofire'
  # pod 'AlamofireImage'
  pod 'RealmSwift'
  pod 'IQKeyboardManagerSwift'
  pod 'Fakery'
end
