platform :ios, '11.0'

target 'EldritchHorrorCards' do
	use_frameworks!
	inhibit_all_warnings!
	
	pod 'SnapKit'
	pod 'Zip'
	pod "SwiftLint"
	
	pod 'ObjectMapper+Realm'
	pod 'RealmSwift'
	pod 'ObjectMapper', :git => 'https://github.com/alecdoconnor/ObjectMapper.git'
	
	#	pod 'Reveal-SDK', :configurations => ['Debug']
end
