platform :ios, '11.0'

target 'EldritchHorrorCards' do
	use_frameworks!
	inhibit_all_warnings!
	
	pod 'SnapKit'
	pod 'Zip'
	pod "SwiftLint"
	pod 'RealmSwift'
	
	#	pod 'Reveal-SDK', :configurations => ['Debug']
end
